/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Fichas;

import Modelo.Entidades.Cliente;
import Modelo.Repository.CentroRepository;

/**
 *
 * @author usuario
 */
public class FichaCliente extends javax.swing.JDialog {

    /**
     * Creates new form FichaCliente
     *
     * @param parent
     * @param modal
     * @param cliente
     */
    public FichaCliente(java.awt.Frame parent, boolean modal, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txt_codigo_cliente.setText(cliente.getCodigo() + "");
        txt_cif.setText(cliente.getCif() + "");
        txt_nombre_fiscal.setText(cliente.getNombre_fiscal());
        txt_nombre_comercial.setText(cliente.getNombre_comercial());
        txt_facturacion.setText(cliente.getContacto());
        
        txt_tlf.setText(cliente.getTelefono() + "");
        txt_fax.setText(cliente.getFax() + "");
        txt_movil.setText(cliente.getMovil() + "");
        txt_email.setText(cliente.getEmail() + "");
        
        txt_fecha_alta.setText(cliente.getFecha_alta() + "");
        txt_fecha_baja.setText(cliente.getFecha_baja() + "");
        CentroRepository cr = new CentroRepository();
        txt_facturacion.setText(cr.getFacturacionTotal(cliente.getCodigo()) + "/mes");
        txt_iban.setText(cliente.getIban());
    }
    
    private FichaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        lbl_movil = new javax.swing.JLabel();
        lbl_nombre_comercial = new javax.swing.JLabel();
        lbl_facturacion = new javax.swing.JLabel();
        lbl_tlf = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_responsable2 = new javax.swing.JLabel();
        lbl_nombre_fiscal = new javax.swing.JLabel();
        label_codigo1 = new javax.swing.JLabel();
        lbl_fax = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        label_codigo2 = new javax.swing.JLabel();
        lbl_cif = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Aceptar = new org.edisoncor.gui.button.ButtonRect();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre_fiscal = new javax.swing.JLabel();
        txt_tlf = new javax.swing.JLabel();
        txt_fax = new javax.swing.JLabel();
        txt_nombre_comercial = new javax.swing.JLabel();
        txt_movil = new javax.swing.JLabel();
        txt_cif = new javax.swing.JLabel();
        txt_fecha_alta = new javax.swing.JLabel();
        txt_facturacion = new javax.swing.JLabel();
        txt_fecha_baja = new javax.swing.JLabel();
        txt_email = new javax.swing.JLabel();
        txt_codigo_cliente = new javax.swing.JLabel();
        lbl_contacto1 = new javax.swing.JLabel();
        txt_contacto1 = new javax.swing.JLabel();
        txt_iban = new javax.swing.JLabel();
        lbl_iban2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha de un cliente");
        setMinimumSize(new java.awt.Dimension(900, 550));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 550));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lbl_movil.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_movil.setForeground(new java.awt.Color(153, 153, 153));
        lbl_movil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_movil.setText("Móvil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_movil, gridBagConstraints);

        lbl_nombre_comercial.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nombre_comercial.setForeground(new java.awt.Color(153, 153, 153));
        lbl_nombre_comercial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombre_comercial.setText("Nombre Comercial");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_nombre_comercial, gridBagConstraints);

        lbl_facturacion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_facturacion.setForeground(new java.awt.Color(153, 153, 153));
        lbl_facturacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_facturacion.setText("Facturacion total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_facturacion, gridBagConstraints);

        lbl_tlf.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_tlf.setForeground(new java.awt.Color(153, 153, 153));
        lbl_tlf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tlf.setText("Teléfono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        jPanel2.add(lbl_tlf, gridBagConstraints);

        lbl_codigo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_codigo.setForeground(new java.awt.Color(153, 153, 153));
        lbl_codigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_codigo.setText("Codigo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        jPanel2.add(lbl_codigo, gridBagConstraints);

        lbl_responsable2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_responsable2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_responsable2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_responsable2.setText("Datos del cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        jPanel2.add(lbl_responsable2, gridBagConstraints);

        lbl_nombre_fiscal.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nombre_fiscal.setForeground(new java.awt.Color(153, 153, 153));
        lbl_nombre_fiscal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombre_fiscal.setText("Nombre Fiscal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_nombre_fiscal, gridBagConstraints);

        label_codigo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_codigo1.setForeground(new java.awt.Color(153, 153, 153));
        label_codigo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_codigo1.setText("Fecha de alta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(label_codigo1, gridBagConstraints);

        lbl_fax.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_fax.setForeground(new java.awt.Color(153, 153, 153));
        lbl_fax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fax.setText("Fax");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_fax, gridBagConstraints);

        lbl_email.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(153, 153, 153));
        lbl_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_email.setText("E-mail");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_email, gridBagConstraints);

        label_codigo2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        label_codigo2.setForeground(new java.awt.Color(153, 153, 153));
        label_codigo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_codigo2.setText("Fecha de baja");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(label_codigo2, gridBagConstraints);

        lbl_cif.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_cif.setForeground(new java.awt.Color(153, 153, 153));
        lbl_cif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cif.setText("CIF");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_cif, gridBagConstraints);

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        jPanel2.add(jSeparator1, gridBagConstraints);

        Aceptar.setBackground(new java.awt.Color(204, 204, 204));
        Aceptar.setForeground(new java.awt.Color(51, 51, 51));
        Aceptar.setText("Aceptar");
        Aceptar.setColorDeSombra(new java.awt.Color(204, 204, 204));
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(Aceptar, gridBagConstraints);

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        jPanel2.add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 16;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 15;
        jPanel2.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = 20;
        jPanel2.add(jLabel3, gridBagConstraints);

        txt_nombre_fiscal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_nombre_fiscal.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombre_fiscal.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_nombre_fiscal, gridBagConstraints);

        txt_tlf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_tlf.setForeground(new java.awt.Color(204, 204, 204));
        txt_tlf.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_tlf, gridBagConstraints);

        txt_fax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_fax.setForeground(new java.awt.Color(204, 204, 204));
        txt_fax.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_fax, gridBagConstraints);

        txt_nombre_comercial.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_nombre_comercial.setForeground(new java.awt.Color(204, 204, 204));
        txt_nombre_comercial.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_nombre_comercial, gridBagConstraints);

        txt_movil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_movil.setForeground(new java.awt.Color(204, 204, 204));
        txt_movil.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_movil, gridBagConstraints);

        txt_cif.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_cif.setForeground(new java.awt.Color(204, 204, 204));
        txt_cif.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_cif, gridBagConstraints);

        txt_fecha_alta.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_fecha_alta.setForeground(new java.awt.Color(204, 204, 204));
        txt_fecha_alta.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_fecha_alta, gridBagConstraints);

        txt_facturacion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_facturacion.setForeground(new java.awt.Color(204, 204, 204));
        txt_facturacion.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_facturacion, gridBagConstraints);

        txt_fecha_baja.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_fecha_baja.setForeground(new java.awt.Color(204, 204, 204));
        txt_fecha_baja.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_fecha_baja, gridBagConstraints);

        txt_email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_email.setForeground(new java.awt.Color(204, 204, 204));
        txt_email.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_email, gridBagConstraints);

        txt_codigo_cliente.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_codigo_cliente.setForeground(new java.awt.Color(204, 204, 204));
        txt_codigo_cliente.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_codigo_cliente, gridBagConstraints);

        lbl_contacto1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_contacto1.setForeground(new java.awt.Color(153, 153, 153));
        lbl_contacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_contacto1.setText("Persona de contacto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_contacto1, gridBagConstraints);

        txt_contacto1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_contacto1.setForeground(new java.awt.Color(204, 204, 204));
        txt_contacto1.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel2.add(txt_contacto1, gridBagConstraints);

        txt_iban.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_iban.setForeground(new java.awt.Color(204, 204, 204));
        txt_iban.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        jPanel2.add(txt_iban, gridBagConstraints);

        lbl_iban2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_iban2.setForeground(new java.awt.Color(153, 153, 153));
        lbl_iban2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_iban2.setText("IBAN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        jPanel2.add(lbl_iban2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_AceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FichaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FichaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FichaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FichaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            FichaCliente dialog = new FichaCliente(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRect Aceptar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_codigo1;
    private javax.swing.JLabel label_codigo2;
    private javax.swing.JLabel lbl_cif;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_contacto1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_facturacion;
    private javax.swing.JLabel lbl_fax;
    private javax.swing.JLabel lbl_iban2;
    private javax.swing.JLabel lbl_movil;
    private javax.swing.JLabel lbl_nombre_comercial;
    private javax.swing.JLabel lbl_nombre_fiscal;
    private javax.swing.JLabel lbl_responsable2;
    private javax.swing.JLabel lbl_tlf;
    private javax.swing.JLabel txt_cif;
    private javax.swing.JLabel txt_codigo_cliente;
    private javax.swing.JLabel txt_contacto1;
    private javax.swing.JLabel txt_email;
    private javax.swing.JLabel txt_facturacion;
    private javax.swing.JLabel txt_fax;
    private javax.swing.JLabel txt_fecha_alta;
    private javax.swing.JLabel txt_fecha_baja;
    private javax.swing.JLabel txt_iban;
    private javax.swing.JLabel txt_movil;
    private javax.swing.JLabel txt_nombre_comercial;
    private javax.swing.JLabel txt_nombre_fiscal;
    private javax.swing.JLabel txt_tlf;
    // End of variables declaration//GEN-END:variables
}
/*
package VistasFichas;

import Modelo.Trabajador;
import javax.swing.JFrame;


public class FichaTrabajador extends javax.swing.JDialog {


    public FichaTrabajador(java.awt.Frame parent, boolean modal, Trabajador trabajador) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        txt_codigo.setText(trabajador.getCodigo() + "");
        txt_nombre.setText(trabajador.getNombre());
    }

    private FichaTrabajador(JFrame jFrame, boolean b) {

    }

    
    @SuppressWarnings("unchecked")
                       

    public static void main(String args[]) {
     
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FichaTrabajador dialog = new FichaTrabajador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel txt_codigo;
    private javax.swing.JLabel txt_nombre;
    // End of variables declaration                   
}
 */
