/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Formularios;

import Modelo.Entidades.Usuario;
import Modelo.Repository.SedesRepository;
import Modelo.Repository.UsuarioRepository;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DisenoWeb
 */
public class FormularioUsuario extends javax.swing.JDialog {

    public Usuario usuarioModificar;
    UsuarioRepository repoUsuario;
    SedesRepository repoSedes;

    /**
     * Creates new form FormularioUsuario
     */
    public FormularioUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        iniciarOtrosComponentes();
    }

    /**
     * Creates new form FormularioUsuario
     */
    public FormularioUsuario(java.awt.Frame parent, boolean modal, Usuario usuario) {
        super(parent, modal);
        iniciarOtrosComponentes();
        this.usuarioModificar = usuario;
    }

    private void iniciarOtrosComponentes() {
        initComponents();
        repoUsuario = new UsuarioRepository();
        repoSedes = new SedesRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        jPanel2 = new javax.swing.JPanel();
        lbl_rol = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_Titulo = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        Aceptar = new org.edisoncor.gui.button.ButtonRect();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        txt_nombre = new javax.swing.JTextField();
        lbl_nombrel1 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(903, 682));
        setPreferredSize(new java.awt.Dimension(903, 682));
        setSize(new java.awt.Dimension(903, 682));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRect1.setColorPrimario(new java.awt.Color(102, 102, 102));
        panelRect1.setColorSecundario(new java.awt.Color(204, 204, 204));
        panelRect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setBackground(new java.awt.Color(102, 102, 102));
        panelCurves1.setForeground(new java.awt.Color(0, 0, 0));
        panelCurves1.setOpaque(true);
        panelCurves1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lbl_rol.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_rol.setForeground(new java.awt.Color(204, 204, 204));
        lbl_rol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rol.setText("Rol");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_rol, gridBagConstraints);

        lbl_id.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_id.setForeground(new java.awt.Color(204, 204, 204));
        lbl_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_id.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 100;
        jPanel2.add(lbl_id, gridBagConstraints);

        txt_id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_id.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(txt_id, gridBagConstraints);

        lbl_Titulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_Titulo.setForeground(new java.awt.Color(204, 204, 204));
        lbl_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Titulo.setText("Datos del usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(lbl_Titulo, gridBagConstraints);

        lbl_password.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(204, 204, 204));
        lbl_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_password.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_password, gridBagConstraints);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel2.add(Aceptar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        jPanel2.add(jSeparator2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipady = 20;
        jPanel2.add(jLabel2, gridBagConstraints);

        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione uno" }));
        comboRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRolActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(comboRol, gridBagConstraints);

        txt_nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(txt_nombre, gridBagConstraints);

        lbl_nombrel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_nombrel1.setForeground(new java.awt.Color(204, 204, 204));
        lbl_nombrel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_nombrel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel2.add(lbl_nombrel1, gridBagConstraints);

        txt_pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(txt_pass, gridBagConstraints);

        panelCurves1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 540, 520));

        panelRect1.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 952, 654));

        getContentPane().add(panelRect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -10, 940, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        comprobarCodigo(evt);
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        comprobarNumero(evt);
    }//GEN-LAST:event_txt_idKeyTyped

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        boolean correcto = false;
        try {
            if (!comboRol.getSelectedItem().equals("Seleccione uno")) {//Rol
                if (!txt_id.getText().equals("") && txt_id.getText() != null) {//Id
                    if (!repoUsuario.ifIdExist(Integer.parseInt(txt_id.getText()))) {//Id repetido
                        usuarioModificar.setId(Integer.parseInt(txt_id.getText()));
                        if (txt_nombre.getText() != null && !txt_nombre.getText().equals("")) {//Nombre
                            usuarioModificar.setNombre(txt_nombre.getText());
                            if (txt_pass.getText() != null && !txt_pass.getText().equals("")) {//Pass
                                usuarioModificar.setPassword(Utilidades.Utilidades.encriptaEnMD5(txt_pass.getText()));
                                correcto = true;
                            } else {
                                JOptionPane.showMessageDialog(this, "Necesita ingresar una contraseña", "CONTRASEÑA", JOptionPane.INFORMATION_MESSAGE);
                            }
                        } else {
                            JOptionPane.showMessageDialog(this, "Necesita ingresar un nombre", "NOMBRE", JOptionPane.INFORMATION_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "El id ya existe en la base de datos", "ID", JOptionPane.WARNING_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Necesita ingresar un id", "ID", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Necesita ingresar un Rol", "ROL", JOptionPane.INFORMATION_MESSAGE);
            }
            if (correcto) {
                this.setVisible(false);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "No se pueden meter números en algunos campos", "Errores con los números", JOptionPane.WARNING_MESSAGE);
            System.out.println(e.getMessage());
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Excepcion al meter los datos del formulario", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void comboRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRolActionPerformed

    }//GEN-LAST:event_comboRolActionPerformed

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioUsuario dialog = new FormularioUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRect Aceptar;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombrel1;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_rol;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_pass;
    // End of variables declaration//GEN-END:variables
    private void comprobarNumero(KeyEvent evt) {

        if (Character.isDigit(evt.getKeyChar()) == false) {
            //JOptionPane.showMessageDialog(rootPane, "No puedes introducir letras");
            evt.consume();
        }
    }

    private void comprobarCodigo(KeyEvent evt) {
        try {
            if (repoUsuario.ifIdExist(Integer.parseInt(txt_id.getText())) && lbl_id.getForeground().equals(new java.awt.Color(204, 204, 204))) {
                JOptionPane.showMessageDialog(this, "Codigo usado", "Codigo", JOptionPane.WARNING_MESSAGE);
                lbl_id.setForeground(Color.red);
            } else if (!repoUsuario.ifIdExist(Integer.parseInt(txt_id.getText())) && lbl_id.getForeground().equals(Color.red)) {
                lbl_id.setForeground(new java.awt.Color(204, 204, 204));
            }
        } catch (NumberFormatException e) {

        }
    }
}
