/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Listado;

import Modelo.Entidades.Centro;
import Modelo.Repository.CentroRepository;
import Utilidades.UtilidadesPantalla;

/**
 *
 * @author usuario
 */
public class ListadoCentros extends javax.swing.JFrame {

    CentroRepository repoCentros;
    private boolean isAlreadyOneClick;
    private Centro centroListadoClientes;

    /**
     * Creates new form ListadoCentros
     */
    public ListadoCentros() {
        iniciarOtros();
    }

    public ListadoCentros(String codigo_trabajador) {
        iniciarOtros();
        
    }

    private void iniciarOtros() {
        initComponents();
        repoCentros = new CentroRepository();
        UtilidadesPantalla.centrarTablas(listado_centros);
        UtilidadesPantalla.resolucionPantalla(this);
        listado_centros.getColumnModel().getColumn(0).setMaxWidth(0);
        listado_centros.getColumnModel().getColumn(0).setMinWidth(0);
        listado_centros.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        listado_centros.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        repoCentros.rellenarTablaDefault(listado_centros);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado_centros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Centros");
        setMaximumSize(null);
        setMinimumSize(null);
        setResizable(false);
        setSize(new java.awt.Dimension(300, 150));

        listado_centros.setAutoCreateRowSorter(true);
        listado_centros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listado_centros.setForeground(new java.awt.Color(51, 51, 51));
        listado_centros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "NOMBRE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listado_centros.setGridColor(new java.awt.Color(204, 204, 204));
        listado_centros.setPreferredSize(new java.awt.Dimension(300, 150));
        listado_centros.setRowHeight(30);
        listado_centros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listado_centrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado_centros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listado_centrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado_centrosMouseClicked
        int id_centro = 0;
        Centro c = null;
        id_centro = (Integer) (listado_centros.getValueAt(listado_centros.getSelectedRow(), 0));
        c = repoCentros.getById(id_centro);
        Listado listar = new Listado();
        listar.ListarCentro(c.getCodigo());
    }//GEN-LAST:event_listado_centrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoCentros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListadoCentros().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_centros;
    // End of variables declaration//GEN-END:variables
}
