/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Listado;

import Modelo.Entidades.Centro;
import Modelo.Entidades.Trabajador;
import Modelo.Repository.CentroRepository;
import Utilidades.UtilidadesPantalla;
import Vistas.Fichas.FichaCentros;
import java.awt.Color;
import java.awt.Font;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.table.JTableHeader;

/**
 *
 * @author DisenoWeb
 */
public class ListadoCentrosDialogo extends javax.swing.JDialog {

    private boolean isAlreadyOneClick;
    CentroRepository repoCentros;
    Trabajador trabajadorCentros;
    java.awt.Frame parent;

    /**
     * Creates new form ListadoCentrosDialogo
     *
     * @param parent
     * @param modal
     * @param trabajador
     */
    public ListadoCentrosDialogo(java.awt.Frame parent, boolean modal, Trabajador trabajador) {
        this.parent = parent;
        this.trabajadorCentros = trabajador;
        this.setTitle("Centros de trabajador con codigo: " + trabajador.getNombre() + trabajador.getApellido1() + trabajador.getApellido2());
        iniciarOtros();
        repoCentros.rellenarTablaCentrosByTrabajador(listado_centros, trabajadorCentros.getCodigo());
        String nombre = trabajadorCentros.getNombre() + " " + trabajadorCentros.getApellido1() + " " + trabajadorCentros.getApellido2();
        this.setTitle("Centros de trabajador: " + nombre.toUpperCase());
    }

    private ListadoCentrosDialogo(JFrame jFrame, boolean b) {
        iniciarOtros();
    }

    private void iniciarOtros() {
        initComponents();
        JTableHeader th = listado_centros.getTableHeader();
        th.setFont(new Font("Times New Roman", Font.BOLD, 18));
        th.setForeground(Color.black);
        listado_centros.getTableHeader().setBackground(Color.GRAY);;

        repoCentros = new CentroRepository();
        UtilidadesPantalla.centrarTablas(listado_centros);
        this.setLocationRelativeTo(null);
        listado_centros.getColumnModel().getColumn(0).setMaxWidth(0);
        listado_centros.getColumnModel().getColumn(0).setMinWidth(0);
        listado_centros.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        listado_centros.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado_centros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Centros de trabajador con codigo: ");
        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(300, 200));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setMaximumSize(null);
        jScrollPane1.setMinimumSize(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(285, 180));

        listado_centros.setAutoCreateRowSorter(true);
        listado_centros.setBackground(new java.awt.Color(51, 51, 51));
        listado_centros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listado_centros.setForeground(new java.awt.Color(204, 204, 204));
        listado_centros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "NOMBRE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listado_centros.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        listado_centros.setMaximumSize(new java.awt.Dimension(285, 140));
        listado_centros.setPreferredSize(new java.awt.Dimension(280, 140));
        listado_centros.setRowHeight(30);
        listado_centros.setSelectionBackground(new java.awt.Color(204, 204, 204));
        listado_centros.setSelectionForeground(new java.awt.Color(51, 51, 51));
        listado_centros.setTableHeader(listado_centros.getTableHeader());
        listado_centros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listado_centrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado_centros);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listado_centrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado_centrosMouseClicked
        if (isAlreadyOneClick) {
            Centro centro;
            int id = (Integer) (listado_centros.getValueAt(listado_centros.getSelectedRow(), 0));
            FichaCentros ficha = new FichaCentros(parent, rootPaneCheckingEnabled, repoCentros.getById(id));
            ficha.setVisible(true);
            isAlreadyOneClick = false;
        } else {
            isAlreadyOneClick = true;
            Timer t = new Timer("doubleclickTimer", false);
            t.schedule(new TimerTask() {
                @Override
                public void run() {
                    isAlreadyOneClick = false;
                }
            }, 250);
        }
    }//GEN-LAST:event_listado_centrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoCentrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoCentrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoCentrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoCentrosDialogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            ListadoCentrosDialogo dialog = new ListadoCentrosDialogo(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_centros;
    // End of variables declaration//GEN-END:variables
}
