/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Listado;

import Modelo.Entidades.Centro;
import Modelo.Repository.TrabajadorRepository;
import Modelo.Entidades.Trabajador;
import Utilidades.Utilidades;
import Utilidades.UtilidadesPantalla;
import java.time.LocalDate;

/**
 *
 * @author DisenoWeb
 */
public class ListadoTrabajadores extends javax.swing.JFrame {

    TrabajadorRepository repoTrabajador;
    Utilidades utilidades = new Utilidades();
    Centro centroListadoTrabajadores;

    public ListadoTrabajadores(Centro centro) {
        this.centroListadoTrabajadores = centro;
        iniciarOtrosComponentes();
    }

    /**
     * Creates new form ListadoTrabajadores
     */
    
    public ListadoTrabajadores() {
        iniciarOtrosComponentes();
        repoTrabajador.rellenarTablaDefault(listado_trabajadores);
        //utilidades.rellenarTabla(listado_trabajadores, "trabajadores", "");
    }
    public ListadoTrabajadores(LocalDate fecha) {
        iniciarOtrosComponentes();
        repoTrabajador.rellenarTablaTrabajadoresDisponibles(listado_trabajadores,fecha);
        //utilidades.rellenarTabla(listado_trabajadores, "trabajadores", "");
    }

    public ListadoTrabajadores(Trabajador t) {
        iniciarOtrosComponentes();
        //repoTrabajador.buscarTrabajadoresPorCentrosDeUnCodigoTrabajador(t.getCodigo() + "");
        repoTrabajador.rellenarTablaDefault(listado_trabajadores);
    }
    /**
     * Inicia los componentes generales de la vista.
     */
    private void iniciarOtrosComponentes() {
        repoTrabajador = new TrabajadorRepository();
        initComponents();
        UtilidadesPantalla.centrarTablas(listado_trabajadores);
        UtilidadesPantalla.resolucionPantalla(this);
        listado_trabajadores.getColumnModel().getColumn(0).setMaxWidth(0);
        listado_trabajadores.getColumnModel().getColumn(0).setMinWidth(0);
        listado_trabajadores.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        listado_trabajadores.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado_trabajadores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTADO DE TRABAJADORES");
        setMinimumSize(new java.awt.Dimension(1360, 762));
        setSize(new java.awt.Dimension(1360, 762));

        listado_trabajadores.setAutoCreateRowSorter(true);
        listado_trabajadores.setBackground(new java.awt.Color(204, 204, 204));
        listado_trabajadores.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        listado_trabajadores.setForeground(new java.awt.Color(51, 51, 51));
        listado_trabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "APELLIDOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listado_trabajadores.setRowHeight(30);
        listado_trabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listado_trabajadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listado_trabajadores);
        if (listado_trabajadores.getColumnModel().getColumnCount() > 0) {
            listado_trabajadores.getColumnModel().getColumn(0).setResizable(false);
            listado_trabajadores.getColumnModel().getColumn(1).setResizable(false);
            listado_trabajadores.getColumnModel().getColumn(2).setResizable(false);
            listado_trabajadores.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1348, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listado_trabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listado_trabajadoresMouseClicked
        int id_trabajador = 0;
        id_trabajador = (Integer) (listado_trabajadores.getValueAt(listado_trabajadores.getSelectedRow(), 0));
        /*for (int i = 0; i < utilidades.lista_de_trabajadores.size(); i++) {
            if (utilidades.lista_de_trabajadores.get(i).getId() == id_trabajador) {
                trabajador = utilidades.lista_de_trabajadores.get(i);
            }
        }*/
        Trabajador trabajador = repoTrabajador.getById(id_trabajador);
        Listado listar = new Listado();
        listar.ListarTrabajador(trabajador.getCodigo());
        //FichaTrabajador ficha = new FichaTrabajador(this, rootPaneCheckingEnabled, trabajador);
        //ficha.setVisible(true);
    }//GEN-LAST:event_listado_trabajadoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListadoTrabajadores().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_trabajadores;
    // End of variables declaration//GEN-END:variables
}
