/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Archivos.Clientes;

import Modelo.Entidades.Centro;
import Modelo.Repository.TrabajadorRepository;
import Utilidades.UtilidadesPantalla;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DisenoWeb
 */
public final class VistaAsignarTrabajadores extends javax.swing.JFrame {

    TrabajadorRepository repoTrabajadores;
    TrabajadorRepository repoTrabajadoresCentro;
    /**
     * Creates new form VistaAsignarTrabajadores
     */
    Centro centroAsignarTrabajador;

    public VistaAsignarTrabajadores() {
        iniciarOtros();
    }

    public VistaAsignarTrabajadores(Centro centro) {
        this.centroAsignarTrabajador = centro;
        iniciarOtros();
    }

    public void iniciarOtros() {
        initComponents();
        UtilidadesPantalla.centrarTablas(tablaTrabajadores);
        UtilidadesPantalla.centrarTablas(tablaTrabajadoresCentro);
        UtilidadesPantalla.resolucionPantalla(this);
        tablaTrabajadores.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(0).setMinWidth(0);
        tablaTrabajadores.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTrabajadores.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tablaTrabajadores.getColumnModel().getColumn(1).setMaxWidth(60);
        tablaTrabajadoresCentro.getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTrabajadoresCentro.getColumnModel().getColumn(0).setMinWidth(0);
        tablaTrabajadoresCentro.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        tablaTrabajadoresCentro.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        tablaTrabajadoresCentro.getColumnModel().getColumn(1).setMaxWidth(60);
        repoTrabajadores = new TrabajadorRepository();
        repoTrabajadoresCentro = new TrabajadorRepository();
        repoTrabajadores.rellenarTrabajadoresNoContratados(tablaTrabajadores, centroAsignarTrabajador.getCodigo());
        repoTrabajadoresCentro.rellenarTablaPorCodigoCentro(tablaTrabajadoresCentro, centroAsignarTrabajador.getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRect1 = new org.edisoncor.gui.panel.PanelRect();
        panelCurves1 = new org.edisoncor.gui.panel.PanelCurves();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTrabajadoresCentro = new javax.swing.JTable();
        Panel_botones1 = new org.edisoncor.gui.panel.Panel();
        btnDerecha = new javax.swing.JButton();
        btnIzquierda = new javax.swing.JButton();
        Buscador1 = new javax.swing.JPanel();
        txt_buscador1 = new javax.swing.JTextField();
        btn_buscar1 = new org.edisoncor.gui.button.ButtonIcon();
        Buscador = new javax.swing.JPanel();
        txt_buscador = new javax.swing.JTextField();
        btn_buscar = new org.edisoncor.gui.button.ButtonIcon();
        btnTrabajadores = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRect1.setColorPrimario(new java.awt.Color(102, 102, 102));
        panelRect1.setColorSecundario(new java.awt.Color(204, 204, 204));
        panelRect1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCurves1.setBackground(new java.awt.Color(102, 102, 102));
        panelCurves1.setForeground(new java.awt.Color(0, 0, 0));
        panelCurves1.setOpaque(true);
        panelCurves1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(240, 240, 240));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitulo.setText("Nombre de centro:");
        panelCurves1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1360, 40));

        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "APELLIDOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTrabajadores);

        panelCurves1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, 590));

        tablaTrabajadoresCentro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CODIGO", "NOMBRE", "APELLIDOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTrabajadoresCentro);

        panelCurves1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, -1, 590));

        Panel_botones1.setColorPrimario(new java.awt.Color(102, 102, 102));
        Panel_botones1.setColorSecundario(new java.awt.Color(204, 204, 204));

        btnDerecha.setText("==>");
        btnDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerechaActionPerformed(evt);
            }
        });

        btnIzquierda.setText("<==");
        btnIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzquierdaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_botones1Layout = new javax.swing.GroupLayout(Panel_botones1);
        Panel_botones1.setLayout(Panel_botones1Layout);
        Panel_botones1Layout.setHorizontalGroup(
            Panel_botones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_botones1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_botones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDerecha, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnIzquierda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_botones1Layout.setVerticalGroup(
            Panel_botones1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_botones1Layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(btnDerecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzquierda)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        panelCurves1.add(Panel_botones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 250, 590));

        Buscador1.setBackground(new java.awt.Color(102, 102, 102));
        Buscador1.setForeground(new java.awt.Color(102, 102, 102));

        txt_buscador1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_buscador1.setText("Buscar...");
        txt_buscador1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscador1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscador1FocusLost(evt);
            }
        });
        txt_buscador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscador1KeyReleased(evt);
            }
        });

        btn_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        btn_buscar1.setText("buttonIcon1");
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Buscador1Layout = new javax.swing.GroupLayout(Buscador1);
        Buscador1.setLayout(Buscador1Layout);
        Buscador1Layout.setHorizontalGroup(
            Buscador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscador1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_buscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Buscador1Layout.setVerticalGroup(
            Buscador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Buscador1Layout.createSequentialGroup()
                .addGroup(Buscador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscador1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCurves1.add(Buscador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, -1));

        Buscador.setBackground(new java.awt.Color(102, 102, 102));
        Buscador.setForeground(new java.awt.Color(102, 102, 102));

        txt_buscador.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_buscador.setText("Buscar...");
        txt_buscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_buscadorFocusLost(evt);
            }
        });
        txt_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscadorKeyReleased(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/busqueda.png"))); // NOI18N
        btn_buscar.setText("buttonIcon1");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuscadorLayout = new javax.swing.GroupLayout(Buscador);
        Buscador.setLayout(BuscadorLayout);
        BuscadorLayout.setHorizontalGroup(
            BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txt_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        BuscadorLayout.setVerticalGroup(
            BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscadorLayout.createSequentialGroup()
                .addGroup(BuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCurves1.add(Buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        btnTrabajadores.setBackground(new java.awt.Color(51, 51, 51));
        btnTrabajadores.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/trabajador.png"))); // NOI18N
        btnTrabajadores.setText("Trabajadores sin centro");
        btnTrabajadores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        btnTrabajadores.setPreferredSize(new java.awt.Dimension(150, 40));
        btnTrabajadores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnTrabajadoresItemStateChanged(evt);
            }
        });
        panelCurves1.add(btnTrabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, -1));

        panelRect1.add(panelCurves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1374, 740));

        getContentPane().add(panelRect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, -10, 1380, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_buscadorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscadorKeyReleased
        if (!btnTrabajadores.isSelected()) {
            if (!txt_buscador.getText().isEmpty()) {//SI EL BUSCADOR NO ESTA VACIO, VACIA LA TABLA Y EMPIEZA A BUSCAR CON LOS CARACTERES QUE LE VAMOS INTRODUCIENDO
                DefaultTableModel dm = (DefaultTableModel) tablaTrabajadores.getModel();
                dm.getDataVector().removeAllElements();
                dm.fireTableDataChanged();
                repoTrabajadores.buscar(tablaTrabajadores, txt_buscador.getText());
            } else {//SI POR EL CONTRARIO ESTA VACIO EL BUSCADOR, ENTONCES RELLENA LA TABLA CON TODO
                repoTrabajadores.rellenarTrabajadoresNoContratados(tablaTrabajadores, centroAsignarTrabajador.getCodigo());
            }
        } else {
            if (!txt_buscador.getText().isEmpty()) {//SI EL BUSCADOR NO ESTA VACIO, VACIA LA TABLA Y EMPIEZA A BUSCAR CON LOS CARACTERES QUE LE VAMOS INTRODUCIENDO
                DefaultTableModel dm = (DefaultTableModel) tablaTrabajadores.getModel();
                dm.getDataVector().removeAllElements();
                dm.fireTableDataChanged();
                repoTrabajadores.buscar(tablaTrabajadores, txt_buscador.getText());
            } else {//SI POR EL CONTRARIO ESTA VACIO EL BUSCADOR, ENTONCES RELLENA LA TABLA CON TODO
                repoTrabajadores.filtrarTrabajadoresSinCentro(tablaTrabajadores);
            }
        }
    }//GEN-LAST:event_txt_buscadorKeyReleased

    private void txt_buscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusLost
        if (txt_buscador.getText().length() == 0) {
            txt_buscador.setText("Buscar...");
        }
    }//GEN-LAST:event_txt_buscadorFocusLost

    private void txt_buscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscadorFocusGained
        if (txt_buscador.getText().contains("Buscar...")) {
            txt_buscador.setText("");
        }
    }//GEN-LAST:event_txt_buscadorFocusGained

    private void txt_buscador1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscador1FocusGained
        if (txt_buscador1.getText().contains("Buscar...")) {
            txt_buscador1.setText("");
        }
    }//GEN-LAST:event_txt_buscador1FocusGained

    private void txt_buscador1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_buscador1FocusLost
        if (txt_buscador1.getText().length() == 0) {
            txt_buscador1.setText("Buscar...");
        }
    }//GEN-LAST:event_txt_buscador1FocusLost

    private void txt_buscador1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscador1KeyReleased
        if (!txt_buscador1.getText().isEmpty()) {//SI EL BUSCADOR NO ESTA VACIO, VACIA LA TABLA Y EMPIEZA A BUSCAR CON LOS CARACTERES QUE LE VAMOS INTRODUCIENDO
            DefaultTableModel dm = (DefaultTableModel) tablaTrabajadoresCentro.getModel();
            dm.getDataVector().removeAllElements();
            dm.fireTableDataChanged();
            repoTrabajadoresCentro.buscar(tablaTrabajadoresCentro, txt_buscador1.getText());
        } else {//SI POR EL CONTRARIO ESTA VACIO EL BUSCADOR, ENTONCES RELLENA LA TABLA CON TODO
            repoTrabajadoresCentro.rellenarTablaPorCodigoCentro(tablaTrabajadoresCentro, centroAsignarTrabajador.getCodigo());
        }
    }//GEN-LAST:event_txt_buscador1KeyReleased

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void btnDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDerechaActionPerformed

    private void btnIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIzquierdaActionPerformed

    private void btnTrabajadoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnTrabajadoresItemStateChanged
        if (btnTrabajadores.isSelected()) {
            
            repoTrabajadores.filtrarTrabajadoresSinCentro(tablaTrabajadores);
        } else {
            repoTrabajadores.rellenarTrabajadoresNoContratados(tablaTrabajadores, centroAsignarTrabajador.getCodigo());
        }
    }//GEN-LAST:event_btnTrabajadoresItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAsignarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAsignarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAsignarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAsignarTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAsignarTrabajadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buscador;
    private javax.swing.JPanel Buscador1;
    private org.edisoncor.gui.panel.Panel Panel_botones1;
    private javax.swing.JButton btnDerecha;
    private javax.swing.JButton btnIzquierda;
    private javax.swing.JToggleButton btnTrabajadores;
    private org.edisoncor.gui.button.ButtonIcon btn_buscar;
    private org.edisoncor.gui.button.ButtonIcon btn_buscar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.edisoncor.gui.panel.PanelCurves panelCurves1;
    private org.edisoncor.gui.panel.PanelRect panelRect1;
    private javax.swing.JTable tablaTrabajadores;
    private javax.swing.JTable tablaTrabajadoresCentro;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JTextField txt_buscador;
    private javax.swing.JTextField txt_buscador1;
    // End of variables declaration//GEN-END:variables
}
