/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Principal;

import Utilidades.Utilidades;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;

/**
 *
 * @author DisenoWeb
 */
public class Login_vista extends javax.swing.JFrame {

    private int xx;
    private int xy;
    private boolean logueado = false;
    Utilidades utilidades = new Utilidades();


    /**
     * Creates new form Login
     */
    public Login_vista() {
        initComponents();
        this.setLocationRelativeTo(null); //CENTRAR LA VENTANA DESDE EL INICIO

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        usuario_text = new javax.swing.JTextField();
        contraseña_text = new javax.swing.JPasswordField();
        boton_entrar = new javax.swing.JButton();
        combo_empresas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo gesinformatica.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 120));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SISTEMA DE GESTIÓN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 260, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 30, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundd.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 261, 637));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CONTRASEÑA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 180, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("EMPRESA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 130, 30));

        usuario_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usuario_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuario_textMouseClicked(evt);
            }
        });
        usuario_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuario_textKeyPressed(evt);
            }
        });
        jPanel1.add(usuario_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 180, 30));

        contraseña_text.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contraseña_textMouseClicked(evt);
            }
        });
        contraseña_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraseña_textKeyPressed(evt);
            }
        });
        jPanel1.add(contraseña_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 180, 30));

        boton_entrar.setBackground(new java.awt.Color(153, 204, 255));
        boton_entrar.setText("ENTRAR");
        boton_entrar.setToolTipText("Pulse este boton para entrar");
        boton_entrar.setOpaque(false);
        boton_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_entrarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 120, 30));

        combo_empresas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_empresas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tersum", "Aurum", "Cleaning Consultores" }));
        combo_empresas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_empresasItemStateChanged(evt);
            }
        });
        jPanel1.add(combo_empresas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 130, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("USUARIO");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 180, 30));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo-tersum.png"))); // NOI18N
        jPanel1.add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 40, 490, 290));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();

    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void usuario_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuario_textMouseClicked
        usuario_text.setText("");
    }//GEN-LAST:event_usuario_textMouseClicked

    private void contraseña_textMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseña_textMouseClicked
        contraseña_text.setText("");
    }//GEN-LAST:event_contraseña_textMouseClicked

    private void combo_empresasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_empresasItemStateChanged
        utilidades.elegirImagenEmpresaCombo(this.getCombo_empresas(),this.getImagen());

    }//GEN-LAST:event_combo_empresasItemStateChanged

    private void boton_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_entrarActionPerformed
        logueado = utilidades.loguearse(this.getUsuario_text().getText(), this.getContraseña_text().getText(), this.getCombo_empresas());
        if (logueado) {
            utilidades.cerrar_ventana_actual(this);
        }
    }//GEN-LAST:event_boton_entrarActionPerformed

    private void usuario_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuario_textKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logueado = utilidades.loguearse(this.getUsuario_text().getText(), this.getContraseña_text().getText(), this.getCombo_empresas());
            if (logueado) {
                utilidades.cerrar_ventana_actual(this);
            }
        }
    }//GEN-LAST:event_usuario_textKeyPressed

    private void contraseña_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseña_textKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logueado = utilidades.loguearse(this.getUsuario_text().getText(), this.getContraseña_text().getText(), this.getCombo_empresas());
            if (logueado) {
                 utilidades.cerrar_ventana_actual(this);
            }
        }
    }//GEN-LAST:event_contraseña_textKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
           
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_vista().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton boton_entrar;
    private javax.swing.JComboBox<String> combo_empresas;
    private javax.swing.JPasswordField contraseña_text;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField usuario_text;
    // End of variables declaration//GEN-END:variables

    public int getXx() {
        return xx;
    }

    public void setXx(int xx) {
        this.xx = xx;
    }

    public int getXy() {
        return xy;
    }

    public void setXy(int xy) {
        this.xy = xy;
    }

    public JComboBox<String> getCombo_empresas() {
        return combo_empresas;
    }

    public void setCombo_empresas(JComboBox<String> combo_empresas) {
        this.combo_empresas = combo_empresas;
    }

    public JPasswordField getContraseña_text() {
        return contraseña_text;
    }

    public void setContraseña_text(JPasswordField contraseña_text) {
        this.contraseña_text = contraseña_text;
    }

    public JTextField getUsuario_text() {
        return usuario_text;
    }

    public void setUsuario_text(JTextField usuario_text) {
        this.usuario_text = usuario_text;
    }

    public JLabel getImagen() {
        return imagen;
    }

    public void setImagen(JLabel imagen) {
        this.imagen = imagen;
    }

}
